export default {
    WEBSOCKET : {
        ADDRESS : "ws://192.168.1.96:8080",
        RECONNECT_TIMEOUT : 5000,
        DISTRIB_MESSAGE_INTERNAL : 'internal',
    },
    UBUS : {
        CURRENT_TIME : '$-current-time',
        SUBSCRIBE : '$-subscribe',
    },
    EVENTS : {
        CORE_IS_LOADED : 'core-loaded',
        LAUNCHER_IS_LOADED : 'launcher-loaded',
        DO_SCREEN_REBUILD : 'do-screen-rebuild',
        PUT_CONFIG_ERROR : 'put-config-error',
        PUT_CONFIG_SUCCESS : 'put-config-success',
        ALERT: 'alert',
        WS_STARTING : 'ws-starting',
        WS_STARTED : 'ws-started',
        WS_ERROR : 'ws-error',
        WS_CLOSED : 'ws-closed',
        UBUS_MESSAGE : 'ubus-message',
    },
    ALERT_TYPE :{
        ERROR : 'error',
        SUCCESS : 'success'
    },
    DISPLAY_DEF : {
        theme : 'dark'
    },
    REST : {
        STATE : "/api/state",
        PROFILE : "/manifest",
        CONFIG : "/api/config",
        AP_AVAILABLE : "/api/rescan_net",
        TIME : "/api/time",
    },
    STATE_SECTIONS : {
        NET : "net",
        SYSTEM : "system",
        DISPLAY : "display",
        USER : "user",
        DATETIME : "datetime"
    },
    TIME_ZONES : [
        {"value":"1","offset":"-720","text":"(GMT-12:00) International Date Line West"},
        {"value":"2","offset":"-660","text":"(GMT-11:00) Midway Island, Samoa"},
        {"value":"3","offset":"-600","text":"(GMT-10:00) Hawaii"},
        {"value":"4","offset":"-540","text":"(GMT-09:00) Alaska"},
        {"value":"5","offset":"-480","text":"(GMT-08:00) Pacific Time (US & Canada)"},
        {"value":"6","offset":"-480","text":"(GMT-08:00) Tijuana, Baja California"},
        {"value":"9","offset":"-420","text":"(GMT-07:00) Mountain Time (US & Canada)"},
        {"value":"11","offset":"-360","text":"(GMT-06:00) Central Time (US & Canada)"},
        {"value":"15","offset":"-300","text":"(GMT-05:00) Eastern Time (US & Canada)"},
        {"value":"17","offset":"-240","text":"(GMT-04:00) Atlantic Time (Canada)"},
        {"value":"21","offset":"-210","text":"(GMT-03:30) Newfoundland"},
        {"value":"22","offset":"-180","text":"(GMT-03:00) Brasilia"},
        {"value":"26","offset":"-120","text":"(GMT-02:00) Mid-Atlantic"},
        {"value":"28","offset":"-60","text":"(GMT-01:00) Azores"},
        {"value":"30","offset":"0","text":"(GMT+00:00) Greenwich Mean Time : Dublin, Edinburgh, Lisbon, London"},
        {"value":"31","offset":"60","text":"(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna"},
        {"value":"36","offset":"120","text":"(GMT+02:00) Калининград, Amman, Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius"},
        {"value":"46","offset":"180","text":"(GMT+03:00) Москва, Санкт-Петербург, Волгоград, Kuwait, Riyadh, Baghdad"},
        {"value":"49","offset":"210","text":"(GMT+03:30) Tehran"},
        {"value":"51","offset":"240","text":"(GMT+04:00) Самара, Baku"},
        {"value":"53","offset":"270","text":"(GMT+04:30) Kabul"},
        {"value":"54","offset":"300","text":"(GMT+05:00) Екатеренбург, Islamabad, Karachi, Tashkent"},
        {"value":"57","offset":"330","text":"(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi"},
        {"value":"58","offset":"345","text":"(GMT+05:45) Kathmandu"},
        {"value":"59","offset":"360","text":"(GMT+06:00) Almaty, Astana, Dhaka"},
        {"value":"61","offset":"390","text":"(GMT+06:30) Yangon (Rangoon)"},
        {"value":"63","offset":"420","text":"(GMT+07:00) Новосибирск, Bangkok, Hanoi, Jakarta"},
        {"value":"66","offset":"480","text":"(GMT+08:00) Иркутск, Ulaan Bataar, Kuala Lumpur, Singapore"},
        {"value":"69","offset":"540","text":"(GMT+09:00) Якутск, Osaka, Sapporo, Tokyo, Seoul"},
        {"value":"72","offset":"570","text":"(GMT+09:30) Adelaide, Darwin"},
        {"value":"74","offset":"600","text":"(GMT+10:00) Владивосток, Melbourne, Sydney, Brisbane"},
        {"value":"79","offset":"660","text":"(GMT+11:00) Магадан, Solomon Is., New Caledonia"},
        {"value":"80","offset":"720","text":"(GMT+12:00) Камчастский край, Auckland, Wellington"},
        {"value":"82","offset":"780","text":"(GMT+13:00) Nuku`alofa"}
    ],
    LANGS : {
        AVAILABLE : [
            {text: 'English', value: 'en'},
            {text: 'Русский', value: 'ru'}
        ],
        en : {
            DISPLAY_TITLE : 'Display',
            THEME: 'Theme',
            LANGUAGE: 'Language',
            THEMES: [
                {text: 'Dark', value: 'dark'},
                {text: 'Light', value: 'light'}
            ],
            SUBMIT : 'Submit',
            RESET : 'Reset',
            DEFAULT : 'Default',
            NAME : 'Name',
            PASSWORD: 'Password',
            ACCESS_POINT: 'Access point',
            INTERNET_CONNECTION: 'Internet connection',
            DASHBOARD : 'Dashboard',
            SETTINGS : 'Settings',
            DATE_TIME : 'Date and time',
            CURRENT : 'Current',
            CURRENT_TIME: 'Time',
            NTP_SYNC: 'Synchronize with the Internet',
            IP: 'ip',
            INTERNET: 'Internet',
            DISCONNECTED : 'Disconnected',
            CONNECTED: 'Connected',
            CONFIG_HELPER_HELLO: '<h2>Hello!</h2><br><p> I\'m SmartTank<span class="cpr"></span>. Let me help you with the settings. A few simple steps and I will be ready to use. You can:</p> <ul><li>Control me from any device that supports a WEB browser;</li><li>Control me from anywhere in the world;</li><li>Install applications turning me into different devices</li><li>And much more...</li></ul><br><br><h2>Are you ready?</h2>',
            INTRODUCTION: 'Introduction',
            CONTINUE: 'Continue',
            BACK: 'Back',
            CANCEL: 'Cancel',
            NETWORK: 'Network',
            BEGIN_WORK : 'Completed',
            READY : 'Ready',
            CONFIG_HELPER_READY : '<h2>Great work!</h2><br><p>Now I\'m ready. You can always go back to the settings in the "Settings" section. There you can ask again to help you;) <br><br><h2>Начнем?</h2><br>',
            PASSWORD_NO_CHANGE : 'Password [NO CHANGED]',
            ERROR_AP_NAME : 'Name of SSID is required and at least 6 characters',
            TIME_ZONE : 'Time zone',
            FIRMWARE : 'Firmware',
            NO_CONNECT: '[NO CONNECT]',
            CLOSE: 'Close',
            NETWORK_ERROR : 'Network error. Please check your connection and try again.',
            STATE_ERROR : 'Error of loading state file',
            ERROR_LOAD_APP : 'Error of loading application',
        },
        ru : {
            DISPLAY_TITLE : 'Экран',
            THEME: 'Тема',
            LANGUAGE: 'Язык',
            THEMES: [
                {text: 'Темная', value: 'dark'},
                {text: 'Светлая', value: 'light'}
            ],
            SUBMIT : 'Применить',
            RESET : 'Сброс',
            DEFAULT : 'По умолчанию',
            NAME : 'Наименование',
            PASSWORD: 'Пароль',
            ACCESS_POINT: 'Точка доступа',
            INTERNET_CONNECTION: 'Соединение с Интернет',
            DASHBOARD : 'Рабочий стол',
            SETTINGS : 'Настройки',
            DATE_TIME : 'Дата и время',
            CURRENT : 'Текущее',
            CURRENT_TIME: 'Время',
            NTP_SYNC : "Синхронизировать с Интернет",
            IP: 'ip',
            INTERNET: 'Интернет',
            DISCONNECTED : 'Нет соединения',
            CONNECTED: 'Подключено',
            CONFIG_HELPER_HELLO: '<h2>Привет!</h2><br><p>Я SmartTank<span class="cpr"></span>. Позволь помочь тебе с настройками. Несколько простых шагов и я буду готов к использованию. Ты сможешь:</p> <ul><li>Управлять мной c любого устройства, поддерживающего браузер;</li><li>Управлять мной из любой точки мира;</li><li>Устанавливать приложения превращая меня в различные устройства;</li><ul>И многое другое...</ul></ul><br><br><h2>Начнем?</h2>',
            INTRODUCTION: 'Знакомство',
            CONTINUE: 'Далее',
            BACK: 'Назад',
            CANCEL : 'Отмена',
            NETWORK : 'Сеть',
            BEGIN_WORK : 'Начало работы',
            READY : 'Готово',
            CONFIG_HELPER_READY: '<h2>Отличная работа!</h2><br><p>Теперь я готов. Ты всегда сможешь вернуться к настройкам в разделе "Настройки". Там же ты сможешь вновь попросить помочь тебе меня;) <br><br><h2>Начнем?</h2><br>',
            PASSWORD_NO_CHANGE: 'Пароль [БЕЗ ИЗМЕНЕНИЙ]',
            ERROR_AP_NAME : 'Не менее 6 символов латиницей',
            TIME_ZONE : 'Часовой пояс',
            FIRMWARE : 'Версия системы',
            NO_CONNECT: '[НЕ ПОДКЛЮЧАТЬ]',
            CLOSE: 'Закрыть',
            NETWORK_ERROR : 'Ошибка сети. Проверьте подключение и повторите попытку.',
            STATE_ERROR : 'Ошибка чтения статуса контроллера',
            ERROR_LOAD_APP : 'Ошибка загрузки приложения',
        }
    }
}