export default {
    REST : {
        STATE : "/api/state",
        AP_AVAILABLE : "/api/rescan_net",
        TIME : "/api/time",
    },
    LANGS : {
        AVAILABLE : [
            {text: 'English', value: 'en'},
            {text: 'Русский', value: 'ru'}
        ],
        en : {
            DISPLAY_TITLE : 'Display',
            THEME: 'Theme',
            LANGUAGE: 'Language',
            THEMES: [
                {text: 'Dark', value: 'dark'},
                {text: 'Light', value: 'light'}
            ],
            SUBMIT : 'Submit',
            RESET : 'Reset',
            DEFAULT : 'Default',
            NAME : 'Name',
            PASSWORD: 'Password',
            ACCESS_POINT: 'Access point',
            INTERNET_CONNECTION: 'Internet connection',
            DASHBOARD : 'Dashboard',
            SETTINGS : 'Settings',
            DATE_TIME : 'Date and time',
            CURRENT : 'Current',
            CURRENT_TIME: 'Time',
            NTP_SYNC: 'Synchronize with the Internet',
            IP: 'ip',
            INTERNET: 'Internet',
            DISCONNECTED : 'Disconnected',
            CONNECTED: 'Connected',
            CONFIG_HELPER_HELLO: '<h2>Hello!</h2><br><p> I\'m SmartTank<span class="cpr"></span>. Let me help you with the settings. A few simple steps and I will be ready to use. You can:</p> <ul><li>Control me from any device that supports a WEB browser;</li><li>Control me from anywhere in the world;</li><li>Install applications turning me into different devices</li><li>And much more...</li></ul><br><br><h2>Are you ready?</h2>',
            INTRODUCTION: 'Introduction',
            CONTINUE: 'Continue',
            BACK: 'Back',
            CANCEL: 'Cancel',
            NETWORK: 'Network',
            BEGIN_WORK : 'Completed',
            READY : 'Ready',
            CONFIG_HELPER_READY : '<h2>Great work!</h2><br><p>Now I\'m ready. You can always go back to the settings in the "Settings" section. There you can ask again to help you;) <br><br><h2>Начнем?</h2><br>',
            PASSWORD_NO_CHANGE : 'Password [NO CHANGED]',
            ERROR_AP_NAME : 'Name of SSID is required and at least 6 characters'
        },
        ru : {
            DISPLAY_TITLE : 'Экран',
            THEME: 'Тема',
            LANGUAGE: 'Язык',
            THEMES: [
                {text: 'Темная', value: 'dark'},
                {text: 'Светлая', value: 'light'}
            ],
            SUBMIT : 'Применить',
            RESET : 'Сброс',
            DEFAULT : 'По умолчанию',
            NAME : 'Наименование',
            PASSWORD: 'Пароль',
            ACCESS_POINT: 'Точка доступа',
            INTERNET_CONNECTION: 'Соединение с Интернет',
            DASHBOARD : 'Рабочий стол',
            SETTINGS : 'Настройки',
            DATE_TIME : 'Дата и время',
            CURRENT : 'Текущее',
            CURRENT_TIME: 'Время',
            NTP_SYNC : "Синхронизировать с Интернет",
            IP: 'ip',
            INTERNET: 'Интернет',
            DISCONNECTED : 'Нет соединения',
            CONNECTED: 'Подключено',
            CONFIG_HELPER_HELLO: '<h2>Привет!</h2><br><p>Я SmartTank<span class="cpr"></span>. Позволь помочь тебе с настройками. Несколько простых шагов и я буду готов к использованию. Ты сможешь:</p> <ul><li>Управлять мной c любого устройства, поддерживающего браузер;</li><li>Управлять мной из любой точки мира;</li><li>Устанавливать приложения превращая меня в различные устройства;</li><ul>И многое другое...</ul></ul><br><br><h2>Начнем?</h2>',
            INTRODUCTION: 'Знакомство',
            CONTINUE: 'Далее',
            BACK: 'Назад',
            CANCEL : 'Отмена',
            NETWORK : 'Сеть',
            BEGIN_WORK : 'Начало работы',
            READY : 'Готово',
            CONFIG_HELPER_READY: '<h2>Отличная работа!</h2><br><p>Теперь я готов. Ты всегда сможешь вернуться к настройкам в разделе "Настройки". Там же ты сможешь вновь попросить помочь тебе меня;) <br><br><h2>Начнем?</h2><br>',
            PASSWORD_NO_CHANGE: 'Пароль [БЕЗ ИЗМЕНЕНИЙ]',
            ERROR_AP_NAME : 'Не менее 6 символов латиницей'
        }
    }
}